deepspeedai/DeepSpeed-MII

- examples/local/conversational-example.py
- examples/local/conversational-query-example.py
- examples/local/fill-mask-example.py
- examples/local/fill-mask-query-example.py
- examples/local/question-answering-query-example.py
- mii/config.py
- mii/constants.py
- mii/grpc_related/modelresponse_server.py
- mii/grpc_related/proto/modelresponse.proto
- mii/grpc_related/proto/modelresponse_pb2.py
- mii/models/load_models.py
- mii/models/providers/llm.py
* Exposes two ds-inference parameters: replace_with_kernel_inject and profile_model_time
* Allows float32/16 dtype names
* Adds opt support mapped to HF provider
* Collapse all DS kwargs into single dict
* Allow bloom-176b w. int8
* Iff DS supports enable_qkv_quantization set it to true for bloom-176b
* Update bloom-176b tokenizer to use padding side left and pad token
* Copied changes from #45 into this PR, they are not always needed but still a nice usability feature
> various clean-up

- requirements/requirements.txt
text2image deployments require deepspeed >= 0.7.4
fixes #78
> bump min deepspeed to 0.7.4

- examples/local/question-answering-query-example.py
In the [deployment step](https://github.com/microsoft/DeepSpeed-MII/blob/main/examples/local/question-answering-example.py#L8) the model is named `name + "-qa-deployment"` (not `name + "_deployment"`).
> fix(example): QnA model name

- examples/local/text-generation-zero-example.py
The `aio` config was wrongly placed in the zero config for DeepSpeed settings. Fixed that and confirmed the example is working
> Fix aio config dict in ZeRO text-gen example

- README.md
- mii/constants.py
DS-inference supports xlm-roberta, updating MII to support it.
> Add xlm-roberta

- mii/config.py
- mii/deployment.py
- mii/models/load_models.py
- mii/models/providers/diffusers.py
- mii/models/providers/huggingface.py
- mii/models/score/score_template.py
- tests/test_local_deployment.py
MII can now optionally load models onto system memory initially with the `load_with_sys_mem` option added to the config. This solves a problem when the model takes up nearly all the GPU memory and performing kernel injection requires some additional space, causing OOM errors despite there being enough GPU memory to hold the model.
Also adding the `DTypeEnum` from DeepSpeed to the MII config and unit tests to test this new option
> Improvements to VRAM usage when loading HF models

- mii/models/load_models.py
In a previous PR we changed how we are loading the smaller Bloom variants (i.e., non-176B models) from using the `llm` provider to using the `huggingface` provider. We didn't include the asserts that verify settings are correct when making this change. Adding those asserts here.
> Add Bloom model config checks for HF provider

- tests/test_local_deployment.py
Fix a bug where the models are getting downloaded every time rather than going onto blob storage connected to self-hosted runners.
> Tests use transformers cache for model storage

- mii/__init__.py
- mii/client.py
- mii/models/score/score_template.py
- mii/server.py
- mii/utils.py
Currently `MIIServerClient` works as both server and client, but they do not share much of the code.
This PR aims to split it to two different classes: MIIServer and MIIClient.
We can keep the code for each small and increase the maintainability with this change.
Regarding this change, this PR also removes the flag `use_grpc_server`.
Now gRPC is used for both LOCAL and AML settings and the flag is always set to True in `score.py`.
We can drastically simplify many conditional branches in server and client by removing the flag.
> Separate server and client

- mii/grpc_related/modelresponse_server.py
MII accepts concurrent requests and handles them on multiple threads. However, pipeline or DeepSpeed engine shared among threads are not thread-safe. Thus, results of concurrent requests can be corrupted.
This PR adds a lock to serialize execution of an inference pipeline.
> Add lock to serialize pipeline execution

- examples/local/txt2img-example.py
Stable Diffusion has been updated to 1.5 in the Diffusers library, and the model is now hosted via RunwayML (1.4 was hosted by CompVis)
Model card is here:
https://huggingface.co/runwayml/stable-diffusion-v1-5
This PR updates the example to the new version, which is considered to be more SFW and has better face quality.
> update txt2img example to sd 1.5

- examples/local/txt2img-example.py
- mii/models/load_models.py
We had options like CUDA graph and kernel injections fixed in MII due to an early implementation of Stable Diffusion support in DeepSpeed-inference. Therefore the way we were standing up the Stable Diffusion pipeline was incorrect. Updating MII to match latest DeepSpeed-inference.
See https://github.com/microsoft/DeepSpeed/pull/2941
> Update Stable Diffusion to match latest DeepSpeed-Inference

- mii/batching/ragged_batching.py
This PR includes:
- Display message when we fall into the deadlock caused by inefficient KV cache
- Keep some margin when scheduling requests
> Mitigate the risk of deadlock

- mii/grpc_related/modelresponse_server.py
Fixes #349. We only need to return a response from rank 0 stub.
@tohtana
> Fix for error messages in persistent deployment

- tests/test_deployment.py
We are seeing failures on some runs with the A6000 runner on the DeepSpeed repo. This is due to the multi-replica test having slightly worse performance on that machine that others we have tested. Providing a wider range of accepted performance for now until we figure out why that machine is behaving differently than others.
Example failure:
```
FAILED test_deployment.py::test_multi_replica[query0-nofail-test-dep-local-50050-False-28080-text-generation-facebook/opt-125m-None-True-2] - AssertionError: two queries should take about the same time as one query
assert 0.8824012279510498 == 0.706052303314209 ± 7.1e-02
comparison failed
Obtained: 0.8824012279510498
Expected: 0.706052303314209 ± 7.1e-02
```
@loadams
> Loosen unit test performance assert

- README.md
- mii/api.py
- mii/batching/ragged_batching.py
- tests/conftest.py
- tests/test_pipeline.py
- Add `destroy()` method to pipeline objects
- Add unit tests for pipeline
- Fix kwarg parsing bug, where passing a `model_config` inside a `mii_config` resulted in an empty `model_config`
> Add pipeline unit tests

- README.md
We now support [falcon](https://github.com/microsoft/DeepSpeed/pull/4790) and [mixtral](https://github.com/microsoft/DeepSpeed/pull/4828) models with latest DeepSpeed. Also updated the model counts.
> Update supported models list

- mii/backend/server.py
I add `restful_api_host` into server args list in order to bind with another hostnames beside "localhost".
> Add restful_api_host into server args.

- mii/api.py
- tests/test_arg_parsing.py
Recent change introduced a bug that tries to get a dictionary value from `None`. Fixed that and added unit tests to avoid similar problems in the future.
> fix bug when mii_config is None

- .github/workflows/formatting.yml
- requirements/requirements-dev.txt
- tests/conftest.py
If `test_pipeline` tests run before `test_deployment` tests, we would run into an `Address already in use` error. Needed to destroy the pytorch process group when tearing down the Pipeline object.
> fix address already in use error on UT

- tests/test_model_support.py
Testing a model from each of the support model families. These tests create a random weights checkpoint engine and inject into deepspeed. This saves time running the tests and we only test if they generate output. These are not correctness tests.
> Add model support unit test

- mii/batching/data_classes.py
- mii/batching/generation/logit_processors.py
- mii/batching/ragged_batching.py
- requirements/requirements.txt
(NOTE: This PR requires the new APIs introduced in https://github.com/microsoft/DeepSpeed/pull/4965)
This PR improves the efficiency scheduling for ragged batching.
- Use a new faster API to query KV cache status (94ebae10bae0191f5c3450819285f166f6875bc9)
- Improved efficiency of Top P logits processor by avoiding an inefficient loop (390302476251c9d58ea443900a0388e8d006f19f)
- Skip duplicated check of schedulability (904e5009e2445b830613a8bfb4b5a01634236ab0)
- Use python int values and lists instead of torch tensors to maintain KV cache status. Using torch tensors has a certain overhead and it becomes significant when they are frequently called in loops (bfdb5db019c44df9a642af513ded4a5ac1374be7)
> Improve efficiency of scheduling and token sampiling

- mii/config.py
Currently users can pass kwargs that do nothing to `client.generate` - updating the pydantic config to raise errors when this happens.
> Error on unknown generate fields

- mii/batching/ragged_batching.py
When doing batch inference using the "Non-Persistent Pipeline" method, i.e. using `mii.pipeline`, the order of outputs is arbitrary, and has no correlation with the order of inputs. This becomes especially obvious when the generated outputs are of varying lengths and therefore finish at different times.
In fact, printing the output if this line of code `uids_complete_order.append(uids_running.index(uid))` would make it clear that it is incorrect, given that it outputs the same index multiple times.
I have tested this PR on a single GPU.
> Make the order of outputs the same as the order of inputs when using `mii.pipeline`

- mii/batching/data_classes.py
The batch scheduler updates `max_new_tokens` when it tries to recover from a deadlock.
This always fails because now `max_new_tokens` is a read-only property of the request class.
```python
new_req.max_new_tokens = r.max_new_tokens - len(r.generated_tokens)
```
This PR adds the setter to update `max_new_tokens`. Another option is to create a new request object.
> Fix recovery from deadlock

- mii/batching/ragged_batching.py
- tests/test_deployment.py
- tests/test_ragged_batching.py
> Readable token streaming support

- mii/grpc_related/modelresponse_server.py
There was a bug that would cause outputs to be in not the same order as inputs (same as #384).
> Fix generate output order

- mii/batching/ragged_batching.py
This PRs improves efficiency when we are running out of KV cache.
Currently, we free the KV cache for all ongoing requests when we fail to schedule any request. This PR changes this strategy by only freeing the cache allocated to the last request. This approach reduces the recomputation cost and prevents the generation from getting stuck.
> Improve recovery from KV cache starvation

- tests/legacy/conftest.py
Seeing a failure around conversational task model checks in MII-legacy. This is because the pipeline_tags we get from huggingface no longer include `conversational`. Investigating further the reason for this, but this should fix the problem in our CI for now.
> Disable model check in UT

- mii/api.py
- mii/config.py
- requirements/requirements.txt
Required changes to DS: https://github.com/microsoft/DeepSpeed/pull/5234
> Add quantization config option

- .github/workflows/nv-v100-legacy.yml
- The path to trigger the nv-v100-legacy workflow was incorrect and is now updated.
- The requirements for the runner are updated to use cu117.
[Before](https://github.com/microsoft/DeepSpeed-MII/actions/runs/8501872742/job/23285292094#step:8:138):
================== 27 passed, 5 warnings in 567.11s (0:09:27) ==================
[After](https://github.com/microsoft/DeepSpeed-MII/actions/runs/8545226316/job/23413014086?pr=456):
================== 27 passed, 5 warnings in 562.81s (0:09:22) ==================
> Update GH workflow and workflow runner requirements.

- mii/batching/ragged_batching.py
- scheduling prompt should break when length of request **equals** `max_ragged_sequence_count`
- considering there are flush requests, should use `scheduled_requests.requests_to_run` rather than `scheduled_requests`
@loadams @mrwyattii can you help review this fix? thanks~
> fix max_ragged_sequence_count check in _schedule_prompts

- mii/backend/client.py
- mii/batching/ragged_batching.py
Resolves warnings in nv-a6000-fastgen listed [here](https://github.com/microsoft/DeepSpeed-MII/actions/runs/9099414778/job/25014622676#step:9:69)
```
../mii/backend/client.py:75
/__w/DeepSpeed-MII/DeepSpeed-MII/mii/backend/client.py:75: DeprecationWarning: invalid escape sequence \*
"""
../mii/batching/ragged_batching.py:546
/__w/DeepSpeed-MII/DeepSpeed-MII/mii/batching/ragged_batching.py:546: DeprecationWarning: invalid escape sequence \*
"""
```
rtd-staging branch updated [here](https://github.com/microsoft/DeepSpeed-MII/tree/rtd-staging)
rtd-staging webpage located [here](https://deepspeed-mii.readthedocs.io/en/rtd-staging/deployment.html#mii.backend.client.MIIClient.generate)
> Fix deprecation warning on escaped characters

- mii/batching/ragged_batching.py
- mii/grpc_related/modelresponse_server.py
This PR fixes the issue where the MII server hangs after encountering 9999 exceptions. This issue was initially reported in https://github.com/microsoft/DeepSpeed-MII/issues/489.
> Always Flush UIDs after Exceptions

- mii/legacy/utils.py
- mii/utils.py
- scripts/model_download.py
Effectively mirror the changes from here: https://github.com/microsoft/DeepSpeed/pull/5789
> Update MII to switch from modelid to id

- mii/batching/ragged_batching.py
- mii/legacy/logging.py
The batch scheduler for FastGen is designed to run only on rank 0, but currently it runs on all ranks when TP is enabled. This causes various unexpected behaviors.
This PR fixes this issue by properly settings a device ID and flushing remaining requests.
> Fix scheduling for non-persistent pipeline

- .github/workflows/nv-a6000-fastgen.yml
MII uses transformers which dropped support for python 3.8 in its latest release.  The CI tests used a docker container that was using python 3.8 and this updates to one using python 3.10.
DeepSpeed equivalent PR: https://github.com/microsoft/DeepSpeed/pull/6681
> Update docker container version

- .github/workflows/nv-v100-legacy.yml
The V100 runners now use cuda 12.1, this needed to be updated in the yml in order to run.
> Update labels to acquire new runners
